# Generated by Django 5.2.10 on 2026-01-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_payment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='actual_supplier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost from supplier (may differ from quoted)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_notified',
            field=models.BooleanField(default=False, help_text='Has customer been notified of book arrival?'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_received',
            field=models.BooleanField(default=False, help_text='Has this item been received from supplier?'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit', 'Deposit Paid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], db_index=True, default='unpaid', help_text='Current payment status', max_length=20),
        ),
    ]
