# Generated by Django 5.2.10 on 2026-01-15 21:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('orders', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_margin_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Default profit margin percentage applied to all books', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Default Profit Margin (%)')),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, ILS, etc.)', max_length=3)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost paid to supplier', max_digits=10, verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price sold to customer', max_digits=10, verbose_name='Selling Price')),
                ('profit_margin', models.DecimalField(decimal_places=2, help_text='Calculated profit margin', max_digits=5, verbose_name='Profit Margin (%)')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units purchased')),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='books.book')),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_records', to='orders.order')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to='suppliers.supplier')),
                ('supplier_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_records', to='suppliers.supplierorder')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', '-created_at'], name='pricing_pri_book_id_b22c9c_idx'), models.Index(fields=['supplier', '-created_at'], name='pricing_pri_supplie_9d12cf_idx')],
            },
        ),
    ]
