# Generated by Django 5.2.10 on 2026-01-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name_en', models.CharField(blank=True, max_length=100, verbose_name='First Name (English)')),
                ('last_name_en', models.CharField(blank=True, max_length=100, verbose_name='Last Name (English)')),
                ('first_name_he', models.CharField(blank=True, max_length=100, verbose_name='First Name (Hebrew)')),
                ('last_name_he', models.CharField(blank=True, max_length=100, verbose_name='Last Name (Hebrew)')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Secondary Phone')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['last_name_en', 'first_name_en'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['last_name_en', 'first_name_en'], name='customers_c_last_na_400015_idx'), models.Index(fields=['last_name_he', 'first_name_he'], name='customers_c_last_na_cab80c_idx')],
            },
        ),
    ]
