"""
Django settings for bookstore project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # PostgreSQL specific features
    
    # Third-party apps
    'parler',  # Multilingual models
    'dal',  # django-autocomplete-light
    'dal_select2',
    'django_celery_beat',
    'django_celery_results',
    'post_office',
    'django_tables2',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_htmx',
    'import_export',
    
    # Local apps
    'apps.core',
    'apps.books',
    'apps.customers',
    'apps.orders',
    'apps.suppliers',
    'apps.pricing',
    'apps.inventory',
    'apps.reports',
    'apps.documents',  # Document management
]

# Development apps - debug_toolbar disabled for speed
if DEBUG:
    INSTALLED_APPS += [
        # 'debug_toolbar',  # Commented out - adds 30-50% overhead
        'django_extensions',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

# Debug toolbar disabled for performance - uncomment to enable:
# if DEBUG:
#     MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# THIRD-PARTY APPS CONFIGURATION
# ============================================================================

# Django Parler (Multilingual)
PARLER_LANGUAGES = {
    None: (
        {'code': 'en', 'name': 'English'},
        {'code': 'he', 'name': 'Hebrew'},
    ),
    'default': {
        'fallbacks': ['en'],
        'hide_untranslated': False,
    }
}

# Cache Configuration - Using LocMem for speed (no Redis connection delays)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    }
}

# If you want Redis when it's available, uncomment below:
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'SOCKET_CONNECT_TIMEOUT': 2,
#             'SOCKET_TIMEOUT': 2,
#         }
#     }
# }

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Email Configuration
# Use console backend if SMTP not configured (for development)
_email_user = env('EMAIL_HOST_USER', default='')
if _email_user and _email_user != 'your-email@gmail.com':
    EMAIL_BACKEND = 'post_office.EmailBackend'
    POST_OFFICE = {
        'BACKENDS': {
            'default': 'django.core.mail.backends.smtp.EmailBackend',
        },
        'CELERY_ENABLED': False,  # Disabled until Celery is running
        'DEFAULT_PRIORITY': 'now',
    }
else:
    # Fallback to console for development
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    POST_OFFICE = {
        'BACKENDS': {
            'default': 'django.core.mail.backends.console.EmailBackend',
        },
        'CELERY_ENABLED': False,
        'DEFAULT_PRIORITY': 'now',
    }

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = _email_user
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='bookstore@example.com')
}

# Supabase Configuration
SUPABASE_URL = env('SUPABASE_URL', default='https://dbpkdibyecqnlwrmqwjr.supabase.co')
SUPABASE_ANON_KEY = env('SUPABASE_ANON_KEY', default='')

# SignalWire Configuration (handled via Supabase Edge Functions)
# These are kept for backward compatibility but credentials are stored in Supabase secrets
SIGNALWIRE_PROJECT_ID = env('SIGNALWIRE_PROJECT_ID', default='')
SIGNALWIRE_API_TOKEN = env('SIGNALWIRE_API_TOKEN', default='')
SIGNALWIRE_SPACE_URL = env('SIGNALWIRE_SPACE_URL', default='')
SIGNALWIRE_FROM_NUMBER = env('SIGNALWIRE_FROM_NUMBER', default='')

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django Tables2
DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"

# Debug Toolbar
if DEBUG:
    INTERNAL_IPS = [
        "127.0.0.1",
    ]
