# Generated by Django 5.2.10 on 2026-01-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='Default supplier for ordering this book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_books', to='suppliers.supplier'),
        ),
    ]
