# Generated by Django 5.2.10 on 2026-01-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_sales_report', 'Can view sales reports'), ('view_profit_analysis', 'Can view profit analysis'), ('view_customer_history', 'Can view customer purchase history'), ('export_reports', 'Can export reports'), ('view_dashboard', 'Can view dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
